name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/fastapi_ml
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: pip install -r python_ml/requirements.txt

    - name: Test API (optional)
      run: echo "Write your unit tests here if any"

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Python ML Image
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi_ml:python ./python_ml
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi_ml:python

    - name: Build and Push Java Backend Image
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi_ml:java ./java_backend
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi_ml:java
